# Generated by Django 5.0.7 on 2024-08-11 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boat', '0004_alter_boat_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boat.boat', verbose_name='offer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boat.owner', verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'лодка',
                'verbose_name_plural': 'лодки',
            },
        ),
    ]
