# Generated by Django 5.0.7 on 2024-08-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0004_alter_boat_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='views_counter',
            field=models.PositiveIntegerField(default=0, verbose_name='просмотры'),
        ),
    ]
