# Generated by Django 5.0.7 on 2024-08-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0007_alter_boat_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='опубликовано'),
        ),
    ]
