# Generated by Django 5.0.7 on 2024-08-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0011_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='description',
        ),
        migrations.AddField(
            model_name='version',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='активная'),
        ),
        migrations.AddField(
            model_name='version',
            name='number',
            field=models.PositiveIntegerField(default=1, verbose_name='номер версии'),
            preserve_default=False,
        ),
    ]
