# Generated by Django 4.2 on 2024-08-23 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0012_remove_version_description_version_is_current_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boat',
            options={'ordering': ['-created_at'], 'permissions': [('can_edit_description', 'Can edit description'), ('can_edit_is_published', 'Can edit is_published')], 'verbose_name': 'лодка', 'verbose_name_plural': 'лодки'},
        ),
    ]
